"""inv migration

Revision ID: 0bcbb65edca5
Revises: 36fd6ee444c8
Create Date: 2022-06-06 11:24:25.844313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcbb65edca5'
down_revision = '36fd6ee444c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('referrer', 'ref_id')
    # op.drop_column('referrer', 'referred_deposit')
    op.add_column('transactions', sa.Column('transaction_email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_transaction_email'), 'transactions', ['transaction_email'], unique=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.drop_index(op.f('ix_transactions_transaction_email'), table_name='transactions')
    op.drop_column('transactions', 'transaction_email')
    op.add_column('referrer', sa.Column('referred_deposit', sa.INTEGER(), nullable=True))
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
