"""new migrattion

Revision ID: 2d9dc98f5f81
Revises: 72e2e8087f92
Create Date: 2022-05-29 16:04:33.168031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9dc98f5f81'
down_revision = '72e2e8087f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_status')
    # ### end Alembic commands ###
