"""invest migration

Revision ID: 34434f3014b5
Revises: 6776981b668a
Create Date: 2022-06-05 22:24:17.057673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34434f3014b5'
down_revision = '6776981b668a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer', 'ref_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
