"""newwer migration

Revision ID: 36e9f0177540
Revises: 6bf425457271
Create Date: 2022-05-26 23:35:07.751630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e9f0177540'
down_revision = '6bf425457271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('account_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_balance')
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
