"""investment migration

Revision ID: 4bc9036e778f
Revises: f9205d99ca34
Create Date: 2022-05-31 21:45:29.556289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc9036e778f'
down_revision = 'f9205d99ca34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('investment_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_investments_investment_time'), 'investments', ['investment_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_investment_time'), table_name='investments')
    op.drop_column('investments', 'investment_time')
    # ### end Alembic commands ###
