"""investment migration

Revision ID: 56adec5ece9b
Revises: f9c866746805
Create Date: 2022-06-05 08:29:35.124874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56adec5ece9b'
down_revision = 'f9c866746805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrer', sa.Column('ref_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'referrer', 'users', ['ref_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.drop_constraint(None, 'referrer', type_='foreignkey')
    op.drop_column('referrer', 'ref_id')
    # ### end Alembic commands ###
