"""new migrattion

Revision ID: 72e2e8087f92
Revises: 08ddc74bbed5
Create Date: 2022-05-29 15:49:16.109560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e2e8087f92'
down_revision = '08ddc74bbed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_payouts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_payouts')
    # ### end Alembic commands ###
