"""new migration

Revision ID: 842a79a82959
Revises: cf940a37937d
Create Date: 2022-06-08 03:21:09.476455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842a79a82959'
down_revision = 'cf940a37937d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_time', sa.DateTime(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('share_amount', sa.Integer(), nullable=True),
    sa.Column('share_type', sa.String(length=15), nullable=True),
    sa.Column('share_email', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_id'), 'share', ['id'], unique=False)
    op.create_index(op.f('ix_share_share_email'), 'share', ['share_email'], unique=False)
    op.create_index(op.f('ix_share_share_time'), 'share', ['share_time'], unique=False)
    # op.drop_column('referrer', 'ref_id')
    # op.drop_column('referrer', 'referred_deposit')
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.add_column('referrer', sa.Column('referred_deposit', sa.INTEGER(), nullable=True))
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_share_share_time'), table_name='share')
    op.drop_index(op.f('ix_share_share_email'), table_name='share')
    op.drop_index(op.f('ix_share_id'), table_name='share')
    op.drop_table('share')
    # ### end Alembic commands ###
