"""new migration

Revision ID: 95d01989ed5e
Revises: 01d9c7d9997a
Create Date: 2022-05-25 06:38:44.158578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d01989ed5e'
down_revision = '01d9c7d9997a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_amount')
    # ### end Alembic commands ###
