"""invest migration

Revision ID: a94e06386391
Revises: 8950b1a3159d
Create Date: 2022-06-05 22:10:34.089796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94e06386391'
down_revision = '8950b1a3159d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer', 'ref_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
