"""invest migration

Revision ID: b745ebf3e7e6
Revises: 9064fd342cea
Create Date: 2022-06-05 21:22:27.405598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b745ebf3e7e6'
down_revision = '9064fd342cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'referrer', 'users', ['ref_id'], ['id'])
    op.drop_column('referrer', 'referred_deposit')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.add_column('referrer', sa.Column('referred_deposit', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'referrer', type_='foreignkey')
    # ### end Alembic commands ###
