"""new migration

Revision ID: cf940a37937d
Revises: 0bcbb65edca5
Create Date: 2022-06-07 15:53:24.703955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf940a37937d'
down_revision = '0bcbb65edca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('referrer', 'ref_id')
    # op.drop_column('referrer', 'referred_deposit')
    op.add_column('transactions', sa.Column('receiver_email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_receiver_email'), 'transactions', ['receiver_email'], unique=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.drop_index(op.f('ix_transactions_receiver_email'), table_name='transactions')
    op.drop_column('transactions', 'receiver_email')
    op.add_column('referrer', sa.Column('referred_deposit', sa.INTEGER(), nullable=True))
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
