"""inv migration

Revision ID: d21ff424539d
Revises: b0d6b4cbdf4d
Create Date: 2022-06-06 10:19:02.132646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21ff424539d'
down_revision = 'b0d6b4cbdf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer', 'ref_id')
    op.drop_column('referrer', 'referred_deposit')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrer', ['referrer'], ['id'])
    op.add_column('referrer', sa.Column('referred_deposit', sa.INTEGER(), nullable=True))
    op.add_column('referrer', sa.Column('ref_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
