"""investment migration

Revision ID: f9205d99ca34
Revises: 2d9dc98f5f81
Create Date: 2022-05-30 03:18:14.278701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9205d99ca34'
down_revision = '2d9dc98f5f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('investment_amount', sa.Integer(), nullable=True),
    sa.Column('investment_plan', sa.String(length=15), nullable=True),
    sa.Column('investment_status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
