"""investment migration

Revision ID: f9c866746805
Revises: 4bc9036e778f
Create Date: 2022-06-04 14:57:32.073064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c866746805'
down_revision = '4bc9036e778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrer', sa.Column('referred_deposit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer', 'referred_deposit')
    # ### end Alembic commands ###
